CREATE DATABASE canteen;

USE canteen;

CREATE TABLE users (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100),
email VARCHAR(100),
password VARCHAR(255)
);

CREATE TABLE food_items (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100),
price INT,
image VARCHAR(255),
category VARCHAR(50)
);

CREATE TABLE orders (
id INT AUTO_INCREMENT PRIMARY KEY,
user_id INT,
total INT,
status VARCHAR(50),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);